<?php

function code4md_init_post_types() {
	$labels = array(
		'name'                  => _x( 'Applications', 'Post type general name', 'code4md' ),
		'singular_name'         => _x( 'Application', 'Post type singular name', 'code4md' ),
		'menu_name'             => _x( 'Applications', 'Admin Menu text', 'code4md' ),
		'name_admin_bar'        => _x( 'Application', 'Add New on Toolbar', 'code4md' ),
		'add_new'               => __( 'Add New', 'code4md' ),
		'add_new_item'          => __( 'Add New application', 'code4md' ),
		'new_item'              => __( 'New application', 'code4md' ),
		'edit_item'             => __( 'Edit application', 'code4md' ),
		'view_item'             => __( 'View application', 'code4md' ),
		'all_items'             => __( 'All applications', 'code4md' ),
		'search_items'          => __( 'Search applications', 'code4md' ),
		'parent_item_colon'     => __( 'Parent applications:', 'code4md' ),
		'not_found'             => __( 'No applications found.', 'code4md' ),
		'not_found_in_trash'    => __( 'No applications found in Trash.', 'code4md' ),
		'featured_image'        => _x( 'Application Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'code4md' ),
		'set_featured_image'    => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'use_featured_image'    => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'archives'              => _x( 'Application archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'code4md' ),
		'insert_into_item'      => _x( 'Add into application', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'code4md' ),
		'uploaded_to_this_item' => _x( 'Uploaded to this application', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'code4md' ),
		'filter_items_list'     => _x( 'Filter applications list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'code4md' ),
		'items_list_navigation' => _x( 'Applications list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'code4md' ),
		'items_list'            => _x( 'Applications list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'code4md' ),
	);
	$args = array(
		'labels'             => $labels,
		'description'        => 'Application custom post type.',
		'public'             => true,
		'publicly_queryable' => true,
		'show_ui'            => true,
		'show_in_menu'       => true,
		'query_var'          => true,
		'rewrite'            => array( 'slug' => 'application' ),
		'capability_type'    => 'post',
		'has_archive'        => true,
		'hierarchical'       => false,
		'menu_position'      => 20,
		'supports'           => array( 'title', 'editor', 'thumbnail', 'revisions' ),
		'taxonomies'         => array( 'post_tag' ),
		'show_in_rest'       => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'application',
		'graphql_plural_name' => 'applications',
	);

	register_post_type( 'Application', $args );

	$labels = array(
		'name'                  => _x( 'Sponsors', 'Post type general name', 'code4md' ),
		'singular_name'         => _x( 'Sponsor', 'Post type singular name', 'code4md' ),
		'menu_name'             => _x( 'Sponsors', 'Admin Menu text', 'code4md' ),
		'name_admin_bar'        => _x( 'Sponsor', 'Add New on Toolbar', 'code4md' ),
		'add_new'               => __( 'Add New', 'code4md' ),
		'add_new_item'          => __( 'Add New sponsor', 'code4md' ),
		'new_item'              => __( 'New sponsor', 'code4md' ),
		'edit_item'             => __( 'Edit sponsor', 'code4md' ),
		'view_item'             => __( 'View sponsor', 'code4md' ),
		'all_items'             => __( 'All sponsors', 'code4md' ),
		'search_items'          => __( 'Search sponsors', 'code4md' ),
		'parent_item_colon'     => __( 'Parent sponsors:', 'code4md' ),
		'not_found'             => __( 'No sponsors found.', 'code4md' ),
		'not_found_in_trash'    => __( 'No sponsors found in Trash.', 'code4md' ),
		'featured_image'        => _x( 'Sponsor Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'code4md' ),
		'set_featured_image'    => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'use_featured_image'    => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'archives'              => _x( 'Sponsor archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'code4md' ),
		'insert_into_item'      => _x( 'Add into sponsor', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'code4md' ),
		'uploaded_to_this_item' => _x( 'Uploaded to this sponsor', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'code4md' ),
		'filter_items_list'     => _x( 'Filter sponsors list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'code4md' ),
		'items_list_navigation' => _x( 'Sponsors list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'code4md' ),
		'items_list'            => _x( 'Sponsors list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'code4md' ),
	);
	$args = array(
		'labels'             => $labels,
		'description'        => 'Sponsor custom post type.',
		'public'             => true,
		'publicly_queryable' => true,
		'show_ui'            => true,
		'show_in_menu'       => true,
		'query_var'          => true,
		'rewrite'            => array( 'slug' => 'sponsor' ),
		'capability_type'    => 'post',
		'has_archive'        => true,
		'hierarchical'       => false,
		'menu_position'      => 20,
		'supports'           => array( 'title', 'editor', 'thumbnail', 'revisions' ),
		'taxonomies'         => array( 'post_tag' ),
		'show_in_rest'       => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'sponsor',
		'graphql_plural_name' => 'sponsors',
	);

	register_post_type( 'Sponsor', $args );

	$labels = array(
		'name'                  => _x( 'Volunteers', 'Post type general name', 'code4md' ),
		'singular_name'         => _x( 'Volunteer', 'Post type singular name', 'code4md' ),
		'menu_name'             => _x( 'Volunteers', 'Admin Menu text', 'code4md' ),
		'name_admin_bar'        => _x( 'Volunteer', 'Add New on Toolbar', 'code4md' ),
		'add_new'               => __( 'Add New', 'code4md' ),
		'add_new_item'          => __( 'Add New volunteer', 'code4md' ),
		'new_item'              => __( 'New volunteer', 'code4md' ),
		'edit_item'             => __( 'Edit volunteer', 'code4md' ),
		'view_item'             => __( 'View volunteer', 'code4md' ),
		'all_items'             => __( 'All volunteers', 'code4md' ),
		'search_items'          => __( 'Search volunteers', 'code4md' ),
		'parent_item_colon'     => __( 'Parent volunteers:', 'code4md' ),
		'not_found'             => __( 'No volunteers found.', 'code4md' ),
		'not_found_in_trash'    => __( 'No volunteers found in Trash.', 'code4md' ),
		'featured_image'        => _x( 'Volunteer Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'code4md' ),
		'set_featured_image'    => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'use_featured_image'    => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'code4md' ),
		'archives'              => _x( 'Volunteer archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'code4md' ),
		'insert_into_item'      => _x( 'Add into volunteer', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'code4md' ),
		'uploaded_to_this_item' => _x( 'Uploaded to this volunteer', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'code4md' ),
		'filter_items_list'     => _x( 'Filter volunteers list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'code4md' ),
		'items_list_navigation' => _x( 'Volunteers list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'code4md' ),
		'items_list'            => _x( 'Volunteers list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'code4md' ),
	);
	$args = array(
		'labels'             => $labels,
		'description'        => 'Volunteer custom post type.',
		'public'             => true,
		'publicly_queryable' => true,
		'show_ui'            => true,
		'show_in_menu'       => true,
		'query_var'          => true,
		'rewrite'            => array( 'slug' => 'volunteer' ),
		'capability_type'    => 'post',
		'has_archive'        => true,
		'hierarchical'       => false,
		'menu_position'      => 20,
		'supports'           => array( 'title', 'editor', 'thumbnail', 'revisions' ),
		'taxonomies'         => array( 'post_tag' ),
		'show_in_rest'       => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'volunteer',
		'graphql_plural_name' => 'volunteers',
	);

	register_post_type( 'Volunteer', $args );
}
add_action( 'init', 'code4md_init_post_types' );
